### ISSUE TITLE
Migration History is getting overwritten

### ISSUE THREAD

**Issue by danielmackay** [aspnet/EntityFramework6#186]
We have a SQL database that we are managing via entity framework migrations and we have 3 DbContexts, each with their own migrations. This works well most of the time, however, we have an issue from time to time where the context key for 2 of the migrations, gets overridden with a context key from another migration. i.e

![](https://i.stack.imgur.com/Z5X1Q.png)

However, it should look like:

![](https://i.stack.imgur.com/fHTrJ.png)

I'm not sure how this would even be possible, but I'm hoping you can give me some indication as to where to look to resolve this.

### Steps to reproduce
I'm not sure of the steps to reproduce this as it is a large application with 3 DbContexts (each with their own migrations).

### Further technical details
- EF 6.1.3
- VS2015 with latest update
- ASP.NET 4.6
- MVC / Web API 5.2.3
- Deployed to Azure App Service (this is where we see the behavior)
- Several web jobs also running within the app service
- SQL Azure DB

**Comment by rowanmiller** [comment]
@danielmackay is there any particular operation you are doing before this happens? Moving migrations history table etc.

**Comment by danielmackay** [comment]
@rowanmiller not that I'm aware of I'm afraid. Something to bear in mind is that we have about 6  webjobs that are all using the same DbContexts to access the DB at the same time as the website.  I'm not sure if this could be a concurrency issue.

**Comment by anpete** [comment]
@danielmackay How are the migrations being run? I.e. Command line or automated via DbMigrator? Are you able to capture the SQL that was generated, that would help a lot in understanding what is going on here.

**Comment by danielmackay** [comment]
@anpete as the website is being hosted in Azure we are running the migrations via DbMigrator.  The migration configuration is set in the DbContext, but we force this to run from Global.asax.  See the attached zip.

I could probably get the SQL generated for the initial create.  But not the sql generated causing the MigrationHistory to be overridden.  As we're not quite sure when that happens, it makes it hard to capture.

[Migrations.zip](https://github.com/aspnet/EntityFramework6/files/746138/Migrations.zip)

**Comment by anpete** [comment]
@danielmackay Can you share the MigrationsConfiguration?

**Comment by danielmackay** [comment]
@anpete - sure.  See the attached.

[MigrationConfiguration.zip](https://github.com/aspnet/EntityFramework6/files/746444/MigrationConfiguration.zip)

**Comment by anpete** [comment]
@danielmackay I'm having a hard time figuring this out. I notice that the number of migrations is different in both screen shots. Is it that case that Migrations are also being lost when this behavior occurs?

Also, can you check whether the ContextKey column on the history table has a default constraint?

**Comment by danielmackay** [comment]
@anpete The screenshots were taken from 2 different databases.  One in production and one in from Dev.  That's why the number of migrations is different.  The main point though, is that when the DB is deployed the migrations come from 3 different sources.  Then at some undetermined time later, all the context keys are overridden from the NotificationContext.

What I want to know / fix is how can these be overridden?

The migration table does not have a default constraint for Context key.  Here is it's definition

`
USE [hcpsprod]
GO

/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 3/02/2017 7:37:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
`

**Comment by anpete** [comment]
@danielmackay Hmmm, I can't see anything in the code that would cause this to happen - We don't ever bulk update the ContextKey column. 

I think we are going to need to do some logging to get to the bottom of this. One way could be to create a custom MigrateDatabaseToLatestVersion initializer that uses DbContext.Database.Log to capture the SQL that is being executed during initialization.

**Comment by danielmackay** [comment]
This has happened again!  This is the 4th time now and is getting really frustrating.  Is entity framework migrations stable enough to be used in the enterprise?

I will implement a log as you've suggested so we can trace this issue.

As a work around, what do you think of changing the schema of using different migration tables for each context?  Is that complicated?

![image](https://cloud.githubusercontent.com/assets/2636640/23287729/e7dd6a3a-fa8a-11e6-80cf-fe4c629c8851.png)

**Comment by danielmackay** [comment]
Also, do you think this could be some sort of race condition between the NotificationContext being used between Web API and many different Web Jobs?

**Comment by SrividyaTR** [comment]
I am facing exactly the same issue what you have described. Will help me greatly in case you have been able to find the root cause for this issue and what is the approach you have taken to resolve/circumvent the issue

**Comment by PeteDurst** [comment]
Hello,

we have exactly the same problem. Our database runs on Azure and currently has two code-first contexts. The last publish of a service resulted in the ContextKey being set to one value in the entire MigrationHistory table. We will now try to split the MigrationHistory as described in [this article](https://msdn.microsoft.com/en-us/library/dn456841%28v=vs.113%29.aspx?f=255&MSPPError=-2147217396). Unfortunately, the error is not reproducible, because we have published without errors to our test environment on Azure.

**Comment by danielmackay** [comment]
This is still not fixed and we have had this happen AGAIN.  Any update on this?

**Comment by medatixxFT** [comment]
We also have the problem that sometimes the ContextKey column of all records is overwritten with the last updated migration.
Currently, we cannot reproduce the behavior. It occurs occasionally with a small percentage of our customers (perhaps 20 out of a few thousand). The error cannot be reproduced by resetting the database and reimporting the migration. That's why we can't find an approach to troubleshooting.
We have three different modules that use the entity framework independently. The modules have no different versions.
Currently, we are helping our customers by replacing the migration history table with a correct version.

**Comment by danielmackay** [comment]
Hi @medatixxFT ,

Previously in our solution we had the database initializer set in a static constructor for the DbContext.  This means that every use of the DbContext would check to see if the DB needed to be upgraded.  The DbContext was being used by multiple processes (asp.net website and several web jobs).  My suspicion is that all these processes concurrently checking and trying to run the same migrations may have caused the problem.

We modified our application so that migrations is disabled: 

`Database.SetInitializer<PSContext>(null);`

We then added a method in our DbContext to manually run the migrations:

```
        public void Migrate()
        {
            var migratorConfig = new Migrations.Configuration();
            var dbMigrator = new DbMigrator(migratorConfig);
            dbMigrator.Update();
        }
```
This method is only ever called once when the website is starting up and is never called by any of the webjobs that use the same DbContext.  Since making that change we have not seen this issue.

Hope that helps your situation.

**Comment by medatixxFT** [comment]
We have not activated automigration. Instead, during the update of our WPF application, a one-time migration is performed by the setup. 
So basically, we're already doing what you suggested. Thanks anyway.
We stay tuned.

**Comment by medatixxFT** [comment]
We could now observe the problem with the overwritten ContextKeys in our systems. However, we cannot reproduce it safely.
After we couldn't reproduce it on our system, it appeared for the first time on a VM with very little memory during our program setup. 
In some repetitions the phenomenon could be observed several times.
Any idears?
We'll keep an eye on it.

**Comment by danielmackay** [comment]
We have changed our app to explicitly run migrations once on start up of
our main app.  It never gets run on any of the numerous webjobs we have.
Since then we have not run into any issues.

**Comment by oiBio** [comment]
today we had exactly the same problem.
We also have several contexts in a migration table. We have activated AutomaticMigration

The SQL server had massive problems this morning (several SHUTDOWN, time outs, low memory etc...) and when the SQL server finally ran again, the migration files were broken as described above. But also not on all websites but only one of eight. 

MS really need to fix this... we are disabling AutomaticMigration for now and i think we use the workaround of @danielmackay

**Comment by ajcvickers** [comment]
We have done significant investigation into this issue and we have been unable to reproduce it when only a single process is initializing/migrating the database. This leads us to believe at this time that this situation only happens when multiple processes/servers can each attempt to initialize/migrate the database at the same time, which is not supported. For example, in the original case, having "the NotificationContext being used between Web API and many different Web Jobs," is definitely not safe.

We will update the documentation to make this clearer, and to further emphasize the dangers of automatically migrating databases as part of startup of a production application. We should try to give better guidance on safe deployment processes that do not involve the production app performing database schema changes.

**Comment by medatixxFT** [comment]
I would like to point out once again that we only have one process that migrates the database once. This executes an explicit migration.

@ajcvickers Did you check that the SQL server has too little memory? oiBio seems to have had the same problem.

**Comment by ajcvickers** [comment]
@medatixxFT Have you been able to find a way to reproduce what you are seeing? If you run your app in a controlled environment over and over again, do you see the issue? Also, what happens if two instances of your WPF app are started at the same time?

**Comment by medatixxFT** [comment]
We have noticed that the problem mainly occurred with customers with outdated or poorly equipped machines. 
So we set up a virtual machine that has little disk space (4GB) and repeat the process. After the second attempt, the problem occurred again. In some of several repetitions the problem occurs regularly. The software setting of our test machine is: SQL Server 2008 R2 (maximum server memory limited to 1024 MB), Windows Server 2008. 
When updating our application, the setup only instantiates the data context for the database migration once. Maybe it should be added that the DataContext contains about 90 tables, if that is relevant. Some of them are updated within a few migrations.
In our opinion it seems to have something to do with the memory size.

**Comment by ButtiBBQ** [comment]
Hi, We have the same issue on 2 customers. This was running for years, now without a change we have this issue on 2 independent customers.  Strange that this after years 2 just. are affected within the same week. Is there any security update that might benefits the issue?

**Comment by XiRioN69** [comment]
We also face the same problem for 1 year now. Very very very random problem. We got problem with somes customers running for years too without problem and one day, boom, migrationHistory table gets down.

Minutes ago, I had the problem by launching my dev application locally (only one process so). The application said that that objects in db already existing... It's effectively the migration table which is down again...

Any workaround about this today ? It's unbeliveable to see that many of us got the problem without any reconstitution at your side...  It's like a time bomb actually

**Comment by shibbard** [comment]
We are also having this problem. We have to then manually go through and set all the contexts, this has happened to 3 out of 20 sites all running in the same Azure App Service Plan. The only consistency I can see with other reports is that before it occured we had run into some memory limitation issues in the App Service.

**Comment by medatixxFT** [comment]
@ajcvickers Have you been able to reproduce the problem by now?
We still have the problem regularly.

Thanks!

**Comment by danielmackay** [comment]
@medatixxFT - Ensure you have only one place in your application (or system) that is triggering the migrations.  That solved the problem for us.

**Comment by ajcvickers** [comment]
@medatixxFT No, I have not been able to reproduce this in any situation where multiple migrations cannot be triggered concurrently.

**Comment by medatixxFT** [comment]
We're not doing that either. We install several modules sequentially during the setup, which migrate their context. In about 25 out of 5000 cases we observe that the ContextKey column is completely overwritten by one module. There is no concurrent migration by different modules.

**Comment by Jojoshua** [comment]
Just experienced this as well on high availability sql server using EF 6.4 Fails on the ExecuteSqlCommand statement because it thinks there are pending migrations.

My setup goes like this...

```
protected void Application_Start()
{
   SetInitializer();
 }

public static void SetInitializer()
{
   Database.SetInitializer(new MigrateDatabaseToLatestVersion<MyContext, Configuration>());

   //Force any pending migrations to run
   var db = new MyContext();
   db.Database.ExecuteSqlCommand("select 1");
   db.Dispose();
}

```

**Comment by JabalSoft** [comment]
We may found the cause! 

We have: 
1. One database.
2. Many .net 4 class libraries (each one has its own context)
3. One  `WinForm` application (exe), That imports all the previews projects.
4. We enable `MigrateDatabaseToLatestVersion` in all the contexts of all projects.
5. Also, when our application starts (Single Process) Aside from `MigrateDatabaseToLatestVersion`  we do the migrate manually using this code for all the contexts (because in some cases we access the data without using EF so we want to make sure all the changes applied to the database)
` var configuration = new Data.Migrations.Configuration();`
` var migrator = new System.Data.Entity.Migrations.DbMigrator(configuration);`
` migrator.Update();`

Everything was ok (For more than 4 months) until last week.
 In one of the projects, we set the `ContextKey` manually instead of depending on the reflection.

Now all of our contexts using reflection to determine their `ContextKey` except in one project we set it manually.

After we set the `ContextKey` manually for one project we start having the same problem described as this issue.

So could our detection be true? 
`Having many contexts with different kinds of setting their keys`.

@danielmackay  Does all of your previews contexts having the same way of setting their keys?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
